-- ============================================
-- USEFUL SQL QUERIES FOR RAILWAY POSTGRESQL
-- iBITS Portal Database Management
-- ============================================

-- ==========================================
-- 1. CHECK IF ADMIN USER EXISTS
-- ==========================================
SELECT 
    "Id", 
    "UserName", 
    "Email", 
    "EmailConfirmed",
    "LockoutEnabled"
FROM "AspNetUsers"
WHERE "Email" = 'admin@ibits.edu.ph';

-- ==========================================
-- 2. CHECK ALL ROLES
-- ==========================================
SELECT * FROM "AspNetRoles"
ORDER BY "Name";

-- ==========================================
-- 3. CHECK ADMIN USER'S ROLES
-- ==========================================
SELECT 
    u."UserName",
    u."Email",
    r."Name" as "RoleName"
FROM "AspNetUsers" u
INNER JOIN "AspNetUserRoles" ur ON u."Id" = ur."UserId"
INNER JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
WHERE u."Email" = 'admin@ibits.edu.ph';

-- ==========================================
-- 4. LIST ALL USERS AND THEIR ROLES
-- ==========================================
SELECT 
    u."UserName",
    u."Email",
    STRING_AGG(r."Name", ', ') as "Roles"
FROM "AspNetUsers" u
LEFT JOIN "AspNetUserRoles" ur ON u."Id" = ur."UserId"
LEFT JOIN "AspNetRoles" r ON ur."RoleId" = r."Id"
GROUP BY u."Id", u."UserName", u."Email"
ORDER BY u."Email";

-- ==========================================
-- 5. MANUALLY CREATE ADMIN USER (if needed)
-- ==========================================
-- First, you need to create the user with a hashed password
-- The password hash below is for: Admin@123
-- WARNING: Use this only if RoleInitializer didn't work

-- Note: This is just an example. The actual password hash 
-- should be generated by ASP.NET Identity

-- ==========================================
-- 6. ASSIGN ADMIN ROLE TO EXISTING USER
-- ==========================================
-- Replace 'user@example.com' with the actual email

INSERT INTO "AspNetUserRoles" ("UserId", "RoleId")
SELECT 
    u."Id",
    r."Id"
FROM "AspNetUsers" u
CROSS JOIN "AspNetRoles" r
WHERE u."Email" = 'your-email@example.com'
AND r."Name" = 'Admin'
AND NOT EXISTS (
    SELECT 1 FROM "AspNetUserRoles" ur2
    WHERE ur2."UserId" = u."Id" 
    AND ur2."RoleId" = r."Id"
);

-- ==========================================
-- 7. CHECK ALL TABLES IN DATABASE
-- ==========================================
SELECT 
    schemaname,
    tablename
FROM pg_catalog.pg_tables
WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
ORDER BY tablename;

-- ==========================================
-- 8. COUNT RECORDS IN EACH TABLE
-- ==========================================
SELECT 
    'AspNetUsers' as table_name, 
    COUNT(*) as record_count 
FROM "AspNetUsers"
UNION ALL
SELECT 'AspNetRoles', COUNT(*) FROM "AspNetRoles"
UNION ALL
SELECT 'AspNetUserRoles', COUNT(*) FROM "AspNetUserRoles"
UNION ALL
SELECT 'Students', COUNT(*) FROM "Students"
UNION ALL
SELECT 'Officers', COUNT(*) FROM "Officers"
UNION ALL
SELECT 'Events', COUNT(*) FROM "Events";

-- ==========================================
-- 9. VERIFY MIGRATIONS APPLIED
-- ==========================================
SELECT * FROM "__EFMigrationsHistory"
ORDER BY "MigrationId";

-- ==========================================
-- 10. DELETE ADMIN USER (BE CAREFUL!)
-- ==========================================
-- Use this only if you need to recreate the admin user
-- WARNING: This will delete the admin user permanently

-- DELETE FROM "AspNetUserRoles" 
-- WHERE "UserId" IN (
--     SELECT "Id" FROM "AspNetUsers" 
--     WHERE "Email" = 'admin@ibits.edu.ph'
-- );

-- DELETE FROM "AspNetUsers" 
-- WHERE "Email" = 'admin@ibits.edu.ph';

-- ==========================================
-- 11. CHECK FOR STUDENTS
-- ==========================================
SELECT 
    "StudentId",
    "FirstName",
    "LastName",
    "Email",
    "Program",
    "YearLevel"
FROM "Students"
ORDER BY "LastName", "FirstName"
LIMIT 10;

-- ==========================================
-- 12. CHECK FOR OFFICERS
-- ==========================================
SELECT 
    "OfficerId",
    "Name",
    "Position",
    "Email",
    "Department"
FROM "Officers"
ORDER BY "Position"
LIMIT 10;

-- ==========================================
-- 13. CONFIRM EMAIL FOR ADMIN USER
-- ==========================================
UPDATE "AspNetUsers"
SET "EmailConfirmed" = true
WHERE "Email" = 'admin@ibits.edu.ph';

-- ==========================================
-- 14. UNLOCK ADMIN USER (if locked out)
-- ==========================================
UPDATE "AspNetUsers"
SET 
    "LockoutEnabled" = false,
    "LockoutEnd" = NULL,
    "AccessFailedCount" = 0
WHERE "Email" = 'admin@ibits.edu.ph';

-- ==========================================
-- 15. GET DATABASE SIZE
-- ==========================================
SELECT 
    pg_size_pretty(pg_database_size(current_database())) as database_size;
