-- ============================================================
-- RESET EVENTS, ATTENDANCE, AND EVENT-BASED FINES
-- ============================================================
-- Description: Safely deletes all event data and resets IDs.
-- ============================================================

use master;




BEGIN TRANSACTION;
BEGIN TRY
    PRINT 'Starting Events Reset...';

    -- 1. Unlink Fines from RemittanceItems
    UPDATE [dbo].[RemittanceItems] 
    SET [FineId] = NULL 
    WHERE [FineId] IN (SELECT FineId FROM [dbo].[Fines] WHERE [AttendanceId] IS NOT NULL);

    -- 2. Delete Fine Payment Transactions linked to Event Fines
    DELETE FROM [dbo].[FinePaymentTransactions]
    WHERE [FineId] IN (SELECT FineId FROM [dbo].[Fines] WHERE [AttendanceId] IS NOT NULL);

    -- 3. Delete Fines generated by Events
    DELETE FROM [dbo].[Fines] WHERE [AttendanceId] IS NOT NULL;

    -- 4. Delete Attendance Records
    DELETE FROM [dbo].[Attendance];

    -- 5. Delete Events
    DELETE FROM [dbo].[Event];

    -- 6. Reset Identity Counters
    DBCC CHECKIDENT ('[dbo].[Event]', RESEED, 0);
    DBCC CHECKIDENT ('[dbo].[Attendance]', RESEED, 0);
    DBCC CHECKIDENT ('[dbo].[Fines]', RESEED, 0);
    DBCC CHECKIDENT ('[dbo].[FinePaymentTransactions]', RESEED, 0);

    COMMIT TRANSACTION;
    
    -- FINAL VERIFICATION TABLE
    SELECT 'Events' as [Module], 'Event' as [Table], COUNT(*) as [Final Count] FROM [dbo].[Event]
    UNION ALL SELECT 'Events', 'Attendance', COUNT(*) FROM [dbo].[Attendance]
    UNION ALL SELECT 'Events', 'Event Fines', COUNT(*) FROM [dbo].[Fines] WHERE [AttendanceId] IS NOT NULL
    UNION ALL SELECT 'Events', 'Fine Transactions', COUNT(*) FROM [dbo].[FinePaymentTransactions];

    PRINT 'SUCCESS: Events Reset Complete. All counts should be 0.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    PRINT 'ERROR: ' + ERROR_MESSAGE();
END CATCH
GO
