// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iBITS_Portal.Models;

#nullable disable

namespace iBITS_Portal.Migrations
{
    [DbContext(typeof(PortaliBitsContext))]
    [Migration("20260208091404_PaymentReminders_AnnouncementsOnly")]
    partial class PaymentReminders_AnnouncementsOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iBITS_Portal.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnouncementType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("int");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Announcements", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.ArchivedAnnouncement", b =>
                {
                    b.Property<int>("ArchivedAnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivedAnnouncementId"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<string>("ArchiveNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ArchiveReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArchivedAnnouncementId");

                    b.ToTable("ArchivedAnnouncements", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.ArchivedEvent", b =>
                {
                    b.Property<int>("ArchivedEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivedEventId"));

                    b.Property<string>("AcadYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchiveNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ArchiveReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AttendanceRecordsAffected")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FineForClassOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FineForMember")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FineForOrgOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonIbitsFineForClassOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonIbitsFineForMember")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonIbitsFineForOrgOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("TotalFinesAffected")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArchivedEventId");

                    b.ToTable("ArchivedEvents", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<string>("AttendanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EventId");

                    b.HasIndex("StudentNum");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("AcadYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FineForClassOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FineForMember")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FineForOrgOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("NonIbitsFineForClassOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonIbitsFineForMember")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NonIbitsFineForOrgOfficer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("EventId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Fee", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeId"));

                    b.Property<string>("AcadYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FeesDueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FeesStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("OfficialPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemittanceId")
                        .HasColumnType("int");

                    b.Property<string>("RemittanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NotRemitted");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FeeId");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("RemittanceId");

                    b.HasIndex("RemittanceStatus");

                    b.HasIndex("StudentNum");

                    b.ToTable("Fees", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FineId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FinesDueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FinesStartDate")
                        .HasColumnType("date");

                    b.Property<string>("FinesStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OfficialPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemittanceId")
                        .HasColumnType("int");

                    b.Property<string>("RemittanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NotRemitted");

                    b.Property<string>("StudentNum")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FineId");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("CollectedBy");

                    b.HasIndex("RemittanceId");

                    b.HasIndex("RemittanceStatus");

                    b.HasIndex("StudentNum");

                    b.ToTable("Fines", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.FinePaymentTransaction", b =>
                {
                    b.Property<int>("FineTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FineTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("FineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FineTransactionId");

                    b.HasIndex("FineId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("StudentNum");

                    b.ToTable("FinePaymentTransactions", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SentBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationId");

                    b.HasIndex("StudentNum");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficerId");

                    b.ToTable("Officers", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("FeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TransactionId");

                    b.HasIndex("FeeId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("StudentNum");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.PendingRoleChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedByAdminId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedByAdminName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeclinedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeclined")
                        .HasColumnType("bit");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OldRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("PendingRoleChanges", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Remittance", b =>
                {
                    b.Property<int>("RemittanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemittanceId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FeeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FineCategory")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RemittanceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("RemittanceId");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("Section");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("ValidatedBy");

                    b.ToTable("Remittances", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.RemittanceItem", b =>
                {
                    b.Property<int>("RemittanceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemittanceItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RemittanceId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RemittanceItemId");

                    b.HasIndex("FeeId");

                    b.HasIndex("FineId");

                    b.HasIndex("RemittanceId");

                    b.HasIndex("StudentNum");

                    b.ToTable("RemittanceItems", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Student", b =>
                {
                    b.Property<string>("StudentNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("ArchiveDate")
                        .HasColumnType("date");

                    b.Property<string>("ArchiveStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Qrcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYearEnrolled")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentMn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearLevelSection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNum");

                    b.HasIndex("OfficerId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.UserAnnouncementDismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentNum")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("StudentNum", "AnnouncementId")
                        .IsUnique()
                        .HasDatabaseName("UQ_StudentAnnouncement");

                    b.ToTable("UserAnnouncementDismissals", (string)null);
                });

            modelBuilder.Entity("iBITS_Portal.Models.Attendance", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Event", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Attendance_Event");

                    b.HasOne("iBITS_Portal.Models.Student", "StudentNumNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Student");

                    b.Navigation("Event");

                    b.Navigation("StudentNumNavigation");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Fee", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Student", "CollectedByNavigation")
                        .WithMany()
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("iBITS_Portal.Models.Remittance", "Remittance")
                        .WithMany()
                        .HasForeignKey("RemittanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("iBITS_Portal.Models.Student", "StudentNumNavigation")
                        .WithMany("Fees")
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fees_Student");

                    b.Navigation("CollectedByNavigation");

                    b.Navigation("Remittance");

                    b.Navigation("StudentNumNavigation");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Fine", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Attendance", "Attendance")
                        .WithMany("Fines")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Fines_Attendance");

                    b.HasOne("iBITS_Portal.Models.Student", "CollectedByNavigation")
                        .WithMany()
                        .HasForeignKey("CollectedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("iBITS_Portal.Models.Remittance", "Remittance")
                        .WithMany()
                        .HasForeignKey("RemittanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("iBITS_Portal.Models.Student", "StudentNumNavigation")
                        .WithMany("Fines")
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Fines_Student");

                    b.Navigation("Attendance");

                    b.Navigation("CollectedByNavigation");

                    b.Navigation("Remittance");

                    b.Navigation("StudentNumNavigation");
                });

            modelBuilder.Entity("iBITS_Portal.Models.FinePaymentTransaction", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Fine", "Fine")
                        .WithMany()
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iBITS_Portal.Models.Student", "Treasurer")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iBITS_Portal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fine");

                    b.Navigation("Student");

                    b.Navigation("Treasurer");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Notification", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Student", "StudentNumNavigation")
                        .WithMany()
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Student");

                    b.Navigation("StudentNumNavigation");
                });

            modelBuilder.Entity("iBITS_Portal.Models.PaymentTransaction", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Fee", "Fee")
                        .WithMany()
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iBITS_Portal.Models.Student", "Treasurer")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iBITS_Portal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Student");

                    b.Navigation("Treasurer");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Remittance", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Student", "SubmittedByNavigation")
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("iBITS_Portal.Models.Student", "ValidatedByNavigation")
                        .WithMany()
                        .HasForeignKey("ValidatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SubmittedByNavigation");

                    b.Navigation("ValidatedByNavigation");
                });

            modelBuilder.Entity("iBITS_Portal.Models.RemittanceItem", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Fee", "Fee")
                        .WithMany()
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("iBITS_Portal.Models.Fine", "Fine")
                        .WithMany()
                        .HasForeignKey("FineId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("iBITS_Portal.Models.Remittance", "Remittance")
                        .WithMany("RemittanceItems")
                        .HasForeignKey("RemittanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iBITS_Portal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Fine");

                    b.Navigation("Remittance");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Student", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Officer", "Officer")
                        .WithMany("Students")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Fk_Officer");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("iBITS_Portal.Models.UserAnnouncementDismissal", b =>
                {
                    b.HasOne("iBITS_Portal.Models.Announcement", "Announcement")
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAnnouncementDismissal_Announcement");

                    b.HasOne("iBITS_Portal.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAnnouncementDismissal_Student");

                    b.Navigation("Announcement");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Attendance", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Event", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Officer", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Remittance", b =>
                {
                    b.Navigation("RemittanceItems");
                });

            modelBuilder.Entity("iBITS_Portal.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Fees");

                    b.Navigation("Fines");
                });
#pragma warning restore 612, 618
        }
    }
}
